-- PAGE NO 38-42 ( FUNCTION)
/*
NOTE :- Full notes Available in Github(@ankushrajmaheyam) or Either copy paste this link( https://www.linkedin.com/posts/ankushrajmaheyam_sql-handwritten-full-notes-ankush-raj-mahe-activity-7261754552075333633-6vMt?utm_source=share&utm_medium=member_desktop ) on any Browser.

*/

-- 78. WAQTD NUMBER OF EMPLOYEES GETTING SALARY LESS THAN 2000 IN DEPTNO 10.
SELECT COUNT(*)
FROM EMP
WHERE SAL<2000 AND DEPTNO = 10;
/*
1
*/


-- 79. WAQTD TOTAL SALARY NEEDED TO PAY EMPLOYEES WORKING AS CLERK.
SELECT SUM(SAL)
FROM EMP
WHERE JOB='CLERK';
/*
4150
*/

-- 80. WAQTD AVERAGE SALARY NEEDED TO PAY ALL EMPLOYEES.
SELECT AVG(SAL)
FROM EMP;
/*
2073.214285714285714285714285714285714286
*/

-- 81. WAQTD NUMBER OF EMPLOYEES HAVING 'A' AS THEIR FIRST CHARACTER.
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE 'A%';
/*
2
*/


-- 82. WAQTD NUMBER OF EMPLOYEES WORKING AS CLERK OR MANAGER.
SELECT COUNT(*)
FROM EMP
WHERE JOB IN ('CLERK', 'MANAGER');

-- 83. WAQTD TOTAL SALARY NEEDED TO PAY EMPLOYEES HIRED IN FEB.
SELECT SUM(SAL)
FROM EMP
WHERE HIREDATE LIKE '%FEB%';
/*
2850
*/

-- 84. WAQTD NUMBER OF EMPLOYEES REPORTING TO 7839(MGR).
SELECT COUNT(*)
FROM EMP
WHERE MGR = 7839;
/*
3
*/

-- 85. WAQTD NUMBER OF EMPLOYEES GETTING COMMISSION IN DEPTNO 30.
SELECT COUNT(*)
FROM EMP
WHERE COMM IS NOT NULL AND DEPTNO = 30;
/*
4
*/

-- 86. WAQTD AVG SAL, TOTAL SAL, NUMBER OF EMPS AND MAXIMUM SALARY GIVEN TO EMPLOYEES WORKING AS PERSIDENT.
SELECT AVG(SAL), SUM(SAL), COUNT(ENAME), MAX(SAL)
FROM EMP
WHERE JOB='PRESIDENT';
/*
5000,5000,1,5000
*/


-- 87. WAQTD NUMBER OF EMPS AND 'A' IN THEIR NAME.
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE '%A%';
/*
7
*/


-- 88. WAQTD NUMBER OF EMPS AND TOTAL SALRY NEEDED TO PAY THE EMPLOYEES WHO HAVE 2 CONSICUTIVE L'S IN THEIR NAMES.
SELECT COUNT(*), SUM(SAL)
FROM EMP
WHERE ENAME LIKE '%LL%';
/*
2,2900
*/


-- 89. WAQTD NUMBER OF DEPARTMENTS PRESENT IN EMPLOYEES TABLE.
SELECT COUNT(DISTINCT(DEPTNO))
FROM EMP;
/*
3
*/


-- 90. WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'Z' IN THEIR NAMES.
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE '%Z%';
/*
0
*/


-- 91. WAQTD NUMBER OF EMPLOYEES HAVING 'S' IN THEIR NAMES.
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE '%S%';
/*
5
*/

-- 92. WAQTD TOTAL SALARY GIVEN TO EMPLOYEES WORKING AS CLERK IN DEPT 30.
SELECT SUM(SAL)
FROM EMP
WHERE JOB='CLERK' AND DEPTNO = 30;
/*
950
*/

-- 93. WAQTD MAXIMUM SALARY GIVEN TO THE EMPLOYEES WORKING AS ANALYST.
SELECT MAX(SAL)
FROM EMP
WHERE JOB='ANALYST';
/*
3000
*/

-- 94. WAQTD NUMBER OF DISTINCT SALARIES PRESENT IN EMPLOYEES TABLE.
SELECT COUNT(DISTINCT(SAL))
FROM EMP;
/*
12
*/

-- 95. WAQTD NUMBER OF JOBS PRESENT IN EMPLOYEES TABLE.
SELECT COUNT(DISTINCT(JOB))
FROM EMP;
/*
5
*/


-- 96. WAQTD AVG SALARY GIVEN TO THE CLERK.
SELECT AVG(SAL)
FROM EMP
WHERE JOB='CLERK';
/*
1037.5
*/


-- 97. WAQTD MINIMUM SALARY GIVEN TO THE EMPLOYEES WHO WORK IN DEPT 10 AS MANAGER OR A CLERK.
SELECT MIN(SAL)
FROM EMP
WHERE DEPTNO = 10 AND JOB IN ('MANAGER', 'CLERK');
/*
1300
*/
